package co.com.ingeneo.utils;



public enum ReportConfigurationCodeEnum {
	
	// --------------- No pertenecen a la configuracion de reportes del usuario ------------
	REPORT_OOSBASE(-1L),
	REPORT_DEALER_RELOAD(-2L),
	REPORT_ACTIVE_POS_BY_TRANSACTIONS(-3L),
	REPORT_POA_ACTIVATION_EMPLOYEE(-4L),
	REPORT_POA_ACTIVATION_GEO_ZONES(-5L),
	REPORT_EPIN_QUERY_MULTIDEALER(-6L),
	// -------------------------------------------------------------------------------------
	REPORT_USERS(1L),
	REPORT_EMPLOYEES(2L),
	REPORT_CIRCUITS(3L),
	REPORT_EPIN_QUERY(4L),
	REPORT_BTS(5L),
	REPORT_SALES(6L),
	REPORT_VISITS(7L),
	REPORT_DEALER_ROUTES(8L),
	REPORT_SUPERVISOR_ROUTE(9L),
	REPORT_OF_CHANGES(10L),	
	REPORT_CONSOLIDATED_EPIN(11L),
	REPORT_EMPLOYEES_ROUTE(12L),
	REPORT_STATE_HISTORICAL_POINTS(13L),
	REPORT_POP_MATERIAL_BY_POS(14L),
	REPORT_PENDING_1(15L),
	HISTORICAL_EPIN_OOS_REPORT_EMPLOYEE(16L),
	HISTORICAL_EPIN_OOS_REPORT_GEOGRAPHIC(17L),
	HISTORICAL_EPIN_OOS_REPORT_COMMERCIAL(18L),
	REPORT_PENDING_2(19L),
	REPORT_PENDING_3(20L),
	REPORT_PENDING_4(21L),
	REPORT_PENDING_5(35L),
	REPORT_POS_REPORT(22L),
	REPORT_CANCELED_1(23L),
	REPORT_CANCELED_2(24L),
	REPORT_CANCELED_3(25L),
	REPORT_SURVEYS_PERFORMED_1(26L),
	REPORT_BALANCE_EPIN_POS(27L),
	REPORT_BALANCE_EPIN_DEALER(28L),
	REPORT_BALANCE_EPIN_EMPLOYEE(29L),
	REPORT_POS_CREATED_MASSIVELY(30L),
	REPORT_SURVEYS_PERFORMED_2(31L),
	REPORT_EPIN_OOS(32L),
	REPORT_EPIN_OOS_GEO_LEVEL(33L),
	REPORT_EPIN_OOS_COM_LEVEL(34L),
	REPORT_ACTIVE_AGENTS_BY_TRANSACTIONS(36L),
	REPORT_DEALERS_STOCK (38L),
	REPORT_SALESMAN_STOCK (39L),
	REPORT_POS_STOCK (40L),
	REPORT_QUERY_SERIALS (41L),
	REPORT_TRANSFER_TRANSACTIONS (42L),
	REPORT_ASSIGNMENT_TRANSACTIONS (43L),
	REPORT_REFUNDMENT_TRANSACTIONS (44L),
	REPORT_GEOFENCING_ALARM(45L),
	REPORT_SALES_VS_FORECAST (46L),
	REPORT_ROUTE_CHANGES_GENERAL_INFO (47L),
	REPORT_ROUTE_CHANGES_EMPLOYEE_INFO (48L),
	REPORT_ROUTE_CHANGES_FREQUENCY_INFO (49L),
	REPORT_EXPORT_PORTAL_AUDITORY (50L);
	private Long reportId;
	
	private ReportConfigurationCodeEnum(Long reportId) {
		this.reportId = reportId;
	}

	public Long getReportId() {
		return reportId;
	}
}
